### ISSUE TITLE
Should export ES5 compatible code for npm

### ISSUE THREAD

**Issue by jennasalau** [kidwm/react-flex-carousel#11]
Nearly every web project (like ours) will ignore folder `node_modules` in webpack loaders.  Usually, babel transform is only applied to the app code, and the node_modules directory is excluded entirely.

Because of this your library throws build errors in our project and I'm very reluctant to run babel over 3rd party libraries.

```
ERROR in 12.9dc888555dd5bb47ea28.chunk.js from UglifyJs
Unexpected token: name (Carousel) [12.9dc888555dd5bb47ea28.chunk.js:1106,6]
```

**Comment by kidwm** [comment]
Thanks for using my work.

Actually, I never use `ignore` in my `babelrc`, since I never assume that every modules I get from npm would always be compatible with the target environment.

because I think that should be done by the user, so I'm very reluctant to do such transformation over my libraries.

BTW, would you like to use `babel-minify` to replace `UglifyJs`?

**Comment by jennasalau** [comment]
Actually we are not using your work and went with another one, thats why I opened the issue for you as a courtesy as others will no doubt do the same.

I wasn't talking about a `babelrc` ignore, I was talking about [webpack loaders](https://webpack.js.org/concepts/loaders/#using-loaders). 

For instance, this is a very common practice.

```
{
        test: /\.(js)$/,
        loader: `babel-loader`,
        exclude: [/node_modules/]
}
```

It would be ridiculous to have to "build" all 3rd party dependencies as well as your app code. Build times would be through the roof! Not to imagine all the "special" configuration issues you would run into.

This is why all the major players ship ES5 UMD ready code such as React, Angular, Vue, Redux etc.... your library is in the minority.

Your reluctant to do this, thats your decision. But i think you should put at the top of your readme in bold that this library has no UMD, _zero_ browser support out of the box and requires you to run babel over it.

**Comment by kidwm** [comment]
Thanks for your suggestion, I'll add it to README soon.

BTW, you can assign a function to `exclude` of webpack loader for more granular customization.
