### ISSUE TITLE
issue with transpiling using babel

### ISSUE THREAD

**Issue by mlp73** [kidwm/react-flex-carousel#7]
Can't get over 'SyntaxError: Unexpected use of reserved word 'let' in strict mode' error thrown in Safari. Using babel through the whole project. This is the only package not transpiling.
Any idea?

**Comment by silviapfeiffer** [comment]
Indeed. While ES6 is not uniformly available, and particularly UglifyJs doesn't understand it, it would be nice if the module included babel.

I'm getting this error:
```
ERROR in developerpage.js from UglifyJs
SyntaxError: Unexpected token: name (Carousel) [./~/react-flex-carousel/index.js:15,0]
```

A module that solves it nicely is react-chartist , if you need an example.
Also, check out: https://mattandre.ws/2015/07/writing-npm-modules-es6-run-es5/

**Comment by silviapfeiffer** [comment]
Yeah, the transpiling is not really working. index.js clashes with UglifyJs for me.

When I manually babel-ify the index.js file, it work though.

**Comment by kidwm** [comment]
Yes, this is a ES2015 module, you may need to add additional setting for it.
Feel free to reopen this issue if you need further instructions.
